dependencies:
  - name: keycloak
    version: "15.0.0"
    repository: "https://codecentric.github.io/helm-charts"
    alias: keycloak
  - name: postgresql
    version: "11.6.15"
    repository: "https://charts.bitnami.com/bitnami"
    alias: keycloak-postgresql  