keycloak:
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - keycloak.local
  extraEnv: |
    - name: DB_VENDOR
      value: POSTGRES
    - name: DB_ADDR
      value: keycloak-postgresql
    - name: DB_DATABASE
      value: keycloak
    - name: DB_USER
      value: keycloak
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-db-secret
          key: password

keycloak-postgresql:
  postgresqlUsername: keycloak
  postgresqlPassword: keycloakpassword
  postgresqlDatabase: keycloak
  service:
    port: 5432

app:
  replicaCount: 2
  image:
    repository: 4836297/big
    tag: first
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - app.local
  keycloak:
    clientId: my-app-client
    secret: super-secret
  database:
    host: app-postgresql
    user: appuser
    password: apppassword
    database: appdb

app-postgresql:
  postgresqlUsername: appuser
  postgresqlPassword: apppassword
  postgresqlDatabase: appdb
  service:
    port: 5432    
