apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
type: Opaque
data:
  password: {{ "apppassword" | b64enc }}

---

apiVersion: v1
kind: Service
metadata:
  name: app-postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: app-postgresql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-postgresql
  template:
    metadata:
      labels:
        app: app-postgresql
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:latest
          env:
            - name: POSTGRES_USER
              value: {{ .Values.app-postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.app-postgresql.postgresqlDatabase }}
          ports:
            - containerPort: 5432
